package service

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const dropInFileName = "crabwise-proxy.conf"
const dropInHeader = "# Generated by crabwise service inject — do not edit manually.\n"

// SystemdManager implements Manager for systemd-based Linux systems.
type SystemdManager struct {
	SystemDirs []string
	UserDirs   []string
	RunCmd     func(name string, args ...string) error
}

// NewSystemdManager returns a SystemdManager with production defaults.
func NewSystemdManager() *SystemdManager {
	home, _ := os.UserHomeDir()
	return &SystemdManager{
		SystemDirs: []string{
			"/etc/systemd/system",
			"/usr/lib/systemd/system",
			"/lib/systemd/system",
		},
		UserDirs: []string{
			filepath.Join(home, ".config", "systemd", "user"),
			"/etc/systemd/user",
		},
		RunCmd: defaultRunCmd,
	}
}

func (m *SystemdManager) Resolve(name string, scope Scope) (Resolution, error) {
	unitName := name + ".service"
	dirs := m.SystemDirs
	dropInRoot := "/etc/systemd/system"

	if scope == ScopeUser {
		dirs = m.UserDirs
		if len(dirs) > 0 {
			dropInRoot = dirs[0]
		}
	}

	for _, dir := range dirs {
		unitPath := filepath.Join(dir, unitName)
		if _, err := os.Stat(unitPath); err == nil {
			return Resolution{
				ServiceName: name,
				Scope:       scope,
				Systemd: &SystemdResolution{
					UnitName:   unitName,
					UnitPath:   unitPath,
					DropInRoot: dropInRoot,
				},
			}, nil
		}
	}

	return Resolution{}, fmt.Errorf("unit %s not found in %s scope (searched: %s)",
		unitName, scope, strings.Join(dirs, ", "))
}

func (m *SystemdManager) Inject(res Resolution, cfg EnvConfig) (InjectResult, error) {
	sd := res.Systemd
	if sd == nil {
		return InjectResult{}, fmt.Errorf("not a systemd resolution")
	}

	dropInDir := filepath.Join(sd.DropInRoot, sd.UnitName+".d")
	dropInPath := filepath.Join(dropInDir, dropInFileName)

	if err := os.MkdirAll(dropInDir, 0755); err != nil {
		return InjectResult{Path: dropInPath}, fmt.Errorf("create drop-in dir: %w", err)
	}

	content := generateSystemdDropIn(cfg)
	if err := os.WriteFile(dropInPath, []byte(content), 0644); err != nil {
		return InjectResult{Path: dropInPath}, fmt.Errorf("write drop-in: %w", err)
	}

	return InjectResult{Path: dropInPath, Written: true}, nil
}

func (m *SystemdManager) Remove(res Resolution, _ EnvConfig) (RemoveResult, error) {
	sd := res.Systemd
	if sd == nil {
		return RemoveResult{}, fmt.Errorf("not a systemd resolution")
	}

	dropInDir := filepath.Join(sd.DropInRoot, sd.UnitName+".d")
	dropInPath := filepath.Join(dropInDir, dropInFileName)

	if _, err := os.Stat(dropInPath); os.IsNotExist(err) {
		return RemoveResult{Path: dropInPath, Removed: false}, nil
	}

	if err := os.Remove(dropInPath); err != nil {
		return RemoveResult{Path: dropInPath}, fmt.Errorf("remove drop-in: %w", err)
	}

	entries, err := os.ReadDir(dropInDir)
	if err == nil && len(entries) == 0 {
		_ = os.Remove(dropInDir)
	}

	return RemoveResult{Path: dropInPath, Removed: true}, nil
}

func (m *SystemdManager) CheckInjected(res Resolution) (bool, error) {
	sd := res.Systemd
	if sd == nil {
		return false, fmt.Errorf("not a systemd resolution")
	}

	dropInPath := filepath.Join(sd.DropInRoot, sd.UnitName+".d", dropInFileName)
	data, err := os.ReadFile(dropInPath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("read drop-in %s: %w", dropInPath, err)
	}

	content := string(data)
	if !strings.HasPrefix(content, dropInHeader) {
		return false, nil
	}
	for _, line := range strings.Split(content, "\n") {
		if strings.Contains(line, "HTTPS_PROXY=") && !strings.HasSuffix(strings.TrimSpace(line), `HTTPS_PROXY=""`) {
			return true, nil
		}
	}
	return false, nil
}

func (m *SystemdManager) Restart(res Resolution) error {
	if res.Scope == ScopeUser {
		if err := m.RunCmd("systemctl", "--user", "daemon-reload"); err != nil {
			return fmt.Errorf("systemctl --user daemon-reload: %w", err)
		}
		return m.RunCmd("systemctl", "--user", "restart", res.ServiceName)
	}
	if err := m.RunCmd("systemctl", "daemon-reload"); err != nil {
		return fmt.Errorf("systemctl daemon-reload: %w", err)
	}
	return m.RunCmd("systemctl", "restart", res.ServiceName)
}

func generateSystemdDropIn(cfg EnvConfig) string {
	var b strings.Builder
	b.WriteString(dropInHeader)
	b.WriteString("[Service]\n")
	for _, env := range ProxyEnvVars(cfg) {
		fmt.Fprintf(&b, "Environment=\"%s=%s\"\n", env.Key, env.Value)
	}
	return b.String()
}
